# Generated by Django 3.2.6 on 2021-08-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='ecommerce.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smart-phones'), ('tablets', 'Tablets'), ('television', 'Television'), ('smartwatches', 'Smart-watches')], max_length=40),
        ),
    ]
